DELIMITER $$
CREATE DEFINER=`eLeapisit`@`%` PROCEDURE `sprocAddOpp`(
in agencyCommitment_v varchar(45),
in applicationDueDate_v datetime(6),
in className_v varchar(45),
in classType_v varchar(45),
in classYear_v varchar(45),
in courseSummary_v varchar(2000),
in createDate_v datetime(6),
in deliverables_v varchar(45),
in description_v varchar(2000),
in donation_v int, 
in duration_v int,
in endDateTime_v datetime(6),
in estimatedClassSize_v int,
in examples_v varchar(45),
in hoursRequired_v int,
in isClass_v tinyint(1),
in isRequiredForClass_v tinyint(1),
in isPaid_v tinyint(1),
in isServiceLearning_v tinyint(1),
in isTeams_v tinyint(1),
in isVirtual_v tinyint(1),
in latitude_v varchar(45),
in location_v varchar(45),
in longitude_v varchar(45),
in minimumPersonsRequired_v int,
in notAllowed_v varchar(45),
in notes_v varchar(45),
in numberOfTeams_v int,
in onBoarding_v varchar(45),
in opportunityType_v varchar(45),
in ownerID_v int,
in pay_v int,
in preferedAgencyType_v varchar(45),
in preferedServiceWorkType_v varchar(45),
in recurrence_v varchar(45),
in requirements_v varchar(45),
in startDateTime_v datetime(6),
in status_v varchar(45),
in supportDescription_v varchar(45),
in supportPreference_v varchar(45),
in teamSize_v int,
in term_v varchar(45),
in timePeriodEndDate_v datetime(6),
in timePeriodStartDate_v datetime(6),
in title_v varchar(45),
in totalSeats_v int
)
BEGIN

/*DECLARE errno INT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
SELECT errno AS MYSQL_ERROR;
ROLLBACK;
END;
START TRANSACTION;*/

INSERT INTO eLeapData.opportunityTable(
    title,
	description,
	startDateTime,
	endDateTime,
	createDate,
	className,
	totalSeats,
	ownerID,
	`status`,
	notes,
	pay,
	donation,
	isPaid,
	isServiceLearning,
	recurrence,
	isVirtual,
	duration,
	timePeriodStartDate,
	timePeriodEndDate,
	location,
	longitude,
	latitude,
	isClass,
	classType,
	term,
	classYear,
	applicationDueDate,
	courseSummary,
	estimatedClassSize,
	isRequiredForClass,
	opportunityType,
	supportPreference,
	onBoarding,
	minimumPersonsRequired,
	isTeams,
	teamSize,
	hoursRequired,
	preferedServiceWorkType,
	preferedAgencyType,
	numberOfTeams,
	examples,
	deliverables,
	agencyCommitment,
	notAllowed,
	requirements,
	supportDescription)
	values
	(title_v,
	description_v,
	startDateTime_v,
	endDateTime_v,
	createDate_v,
	className_v,
	totalSeats_v,
	ownerID_v,
	status_v,
	notes_v,
	pay_v,
	donation_v,
	isPaid_v,
	isServiceLearning_v,
	recurrence_v,
	isVirtual_v,
	duration_v,
	timePeriodStartDate_v,
	timePeriodEndDate_v,
	location_v,
	longitude_v,
	latitude_v,
    isClass_v,
	classType_v,
	term_v,
	classYear_v,
	applicationDueDate_v,
	courseSummary_v,
	estimatedClassSize_v,
	isRequiredForClass_v,
	opportunityType_v,
	supportPreference_v,
	onBoarding_v,
	minimumPersonsRequired_v,
	isTeams_v,
	teamSize_v,
	hoursRequired_v,
	preferedServiceWorkType_v,
	preferedAgencyType_v,
	numberOfTeams_v,
	examples_v,
	deliverables_v,
	agencyCommitment_v,
	notAllowed_v,
	requirements_v,
	supportDescription_v
    );
    SELECT 'success' AS 'status';
    SELECT totalSeats AS 'availableSeats', opportunityTable.* FROM eLeapData.opportunityTable Where eLeapData.opportunityTable.opportunityId = LAST_INSERT_ID(); 
    
   /* COMMIT;*/
END$$
DELIMITER ;
