DELIMITER $$
CREATE DEFINER=`eLeapisit`@`%` PROCEDURE `sprocUpdateOpp`(in oppID int, in Title_v varchar(45),in description_v varchar(45), in StartDate_v DateTime, in EndDate_v datetime,in CreateDate_v DateTime, in ClassID_v int, in TotalSeats_v int, in OwnerID_v int,in StatusID_v varChar(45), in Notes_v varchar(45),in Pay_v smallint,in Donation_v smallint,in IsPaid_v binary,in IsServiceLearning_v binary,in IsRecurrent_v binary,in IsVirtual_v binary,in Duration_v int,in TimePeriodStart_v datetime, in TimePeriodEnd_v datetime, in Location_v varchar(45),in Longitude_v varchar(45),in Latitude_v varchar(45),in isClass_v tinyint(1),in classType_v varchar(45),in term_v varchar(45),in classYear_v varchar(45),in applicationDueDate_v varchar(45),in courseSummary_v varchar(45),in estimatedClassSize_v varchar(45),in isRequiredForClass_v varchar(45),in opportunityType_v varchar(45),in supportPreference_v varchar(45),in onBoarding_v varchar(45),in minimumPersonRequired_v varchar(45),in isTeams_v tinyint(1),in teamSize_v varchar(45),in hoursRequired_v varchar(45),in preferedServiceWorkType_v varchar(45),in preferedAgencyType_v varchar(45),in numberOfTeams_v varchar(45),in examples_v varchar(45),in deliverables_v varchar(45),in agencyCommitment_v varchar(45),in notAllowed_v varchar(45),in requirements_v varchar(45),in supportDescription_v varchar(45))
BEGIN
UPDATE eLeapData.opportunityTable
SET
	OpportunityID = oppID,
	Title = Title_v,
	Description = description_v,
	StartDate = StartDate_v,
	EndDate= EndDate_v,
	CreateDate = CreateDate_v,
	ClassID = ClassID_v,
	TotalSeats = TotalSeats_v,
	OwnerID = OwnerID_v,
	StatusID = StatusID_v,
	Notes = Notes_v,
	Pay = Pay_v,
	Donation = Donation_v,
	IsPaid = IsPaid_v,
	IsServiceLearning = IsServiceLearning_v,
	IsVirtual = IsVirtual_v,
	Duration = Duration_v,
	TimePeriodStart = TimePeriodStart_v,
	TimePeriodEnd = TimePeriodEnd_v,
	Location = Location_v,
	Longitude = Longitude_v,
	Latitude = Latitude_v,
	isClass = isClass_v,
	classType = classType_v,
	term = term_v,
	classYear = classYear_v,
	applicationDueDate = applicationDueDate_v,
	courseSummary =courseSummary_v,
	estimatedClassSize =estimatedClassSize_v,
	isRequiredForClass =isRequiredForClass_v,
	opportunityType =opportunityType_v,
	supportPreference =supportPreference_v,
	onBoarding =onBoarding_v,
	minimumPersonRequired =minimumPersonRequired_v,
	isTeams =isTeams_v,
	teamSize =teamSize_v,
	hoursRequired =hoursRequired_v,
	preferedServiceWorkType =preferedServiceWorkType_v,
	preferedAgencyType =preferedAgencyType_v,
	numberOfTeams =numberOfTeams_v,
	examples =examples_v,
	deliverables =deliverables_v,
	agencyCommitment =agencyCommitment_v,
	notAllowed =notAllowed_v,
	requirements =requirements_v,
	supportDescription =supportDescription_v
;
END$$
DELIMITER ;
