DELIMITER $$
CREATE DEFINER=`eLeapisit`@`%` PROCEDURE `sprocAllOwnClass`(in ownerId_v int)
BEGIN

DECLARE errno INT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
SELECT errno AS MYSQL_ERROR;
ROLLBACK;
END;
START TRANSACTION;
SELECT 
    *
FROM
    `eLeapData`.`collegeClassTable`
WHERE
    ownerId = ownerId_v; 
COMMIT;
END$$
DELIMITER ;
