CREATE TABLE `logTable` (
    `logID` INT(11) NOT NULL,
    `logDetails` VARCHAR(45) DEFAULT NULL,
    `logDate` DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (`logID`)
)  ENGINE=INNODB DEFAULT CHARSET=LATIN1;
