CREATE TABLE `opportunityTable` (
    `opportunityId` INT(11) NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(200) NOT NULL DEFAULT 'Default Title',
    `description` VARCHAR(2000) DEFAULT 'Default Description',
    `startDateTime` DATETIME(6) DEFAULT CURRENT_TIMESTAMP (6),
    `endDateTime` DATETIME(6) DEFAULT CURRENT_TIMESTAMP (6),
    `createDate` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP (6),
    `className` VARCHAR(2000) DEFAULT '0',
    `totalSeats` INT(11) DEFAULT NULL,
    `ownerId` INT(11) NOT NULL DEFAULT '3',
    `status` VARCHAR(2000) DEFAULT 'Pending',
    `notes` VARCHAR(2000) DEFAULT NULL,
    `pay` INT(11) DEFAULT '0',
    `donation` INT(11) DEFAULT NULL,
    `isPaid` TINYINT(1) UNSIGNED ZEROFILL DEFAULT '0',
    `isServiceLearning` TINYINT(1) UNSIGNED ZEROFILL DEFAULT '0',
    `recurrence` VARCHAR(2000) DEFAULT NULL,
    `isVirtual` TINYINT(1) UNSIGNED ZEROFILL DEFAULT '0',
    `duration` INT(11) DEFAULT '0',
    `timePeriodStartDate` DATETIME(6) DEFAULT NULL,
    `timePeriodEndDate` DATETIME(6) DEFAULT NULL,
    `location` VARCHAR(2000) DEFAULT NULL,
    `longitude` VARCHAR(2000) DEFAULT NULL,
    `latitude` VARCHAR(2000) DEFAULT NULL,
    `isClass` TINYINT(1) UNSIGNED ZEROFILL DEFAULT '0',
    `applicationDueDate` DATETIME(6) DEFAULT NULL,
    `isRequiredForClass` TINYINT(1) UNSIGNED ZEROFILL DEFAULT '0',
    `opportunityType` VARCHAR(2000) DEFAULT NULL,
    `supportPreference` VARCHAR(2000) DEFAULT NULL,
    `onBoarding` VARCHAR(2000) DEFAULT NULL,
    `minimumPersonsRequired` INT(11) DEFAULT '0',
    `isTeams` TINYINT(1) UNSIGNED ZEROFILL DEFAULT '0',
    `teamSize` INT(11) DEFAULT '0',
    `hoursRequired` INT(11) DEFAULT '0',
    `preferredServiceWorkType` VARCHAR(2000) DEFAULT NULL,
    `preferredAgencyType` VARCHAR(2000) DEFAULT NULL,
    `numberOfTeams` INT(11) DEFAULT '0',
    `examples` VARCHAR(2000) DEFAULT NULL,
    `deliverables` VARCHAR(2000) DEFAULT NULL,
    `agencyCommitment` VARCHAR(2000) DEFAULT NULL,
    `notAllowed` VARCHAR(2000) DEFAULT NULL,
    `requirements` VARCHAR(2000) DEFAULT NULL,
    `supportDescription` VARCHAR(2000) DEFAULT NULL,
    `lastModified` DATETIME DEFAULT NULL,
    `classId` INT(11) DEFAULT NULL,
    PRIMARY KEY (`opportunityId`),
    UNIQUE KEY `opportunityId_UNIQUE` (`opportunityId`)
)  ENGINE=INNODB AUTO_INCREMENT=158 DEFAULT CHARSET=LATIN1;
